### ISSUE TITLE
Home mini refresh rate stops target sensors  updating

### ISSUE THREAD

**Issue by f1wade** [BottlecapDave/HomeAssistant-OctopusEnergy#435]
### Describe the bug

I have a target sensor that will trigger 2 half hours overnight.
Worked fine at 1 min refresh rate.
I changed to 10 min refresh rate, to save network calls.
And the trigger didn't trigger at all overnight and it should have turned on, off, on, off. For half hour each.

I have changed back to 2 mins, to see if that works better. 

### Reproduction steps

As above

### Expected behaviour

To update correctly. 

### Integration Version

Latest

### Home Assistant Version

2023.7.3

### Fresh Install?

Not specified

### Home Assistant Logs

Will see if any later

**Comment by f1wade** [comment]
1 other thing that changed on the target was I ticked last applicable rates, I've not had that ticked through a cycle.

**Comment by f1wade** [comment]
Update I change to 2 mins and it worked, and then 5 mins and it worked.

**Comment by BottlecapDave** [comment]
Hello and sorry you're having issues. I believe the updating of the mini rates are just a coincidence as the two settings are unrelated. I have sporadic reports of sensors stopping working, which I'm still trying to track down the cause for.

**Comment by f1wade** [comment]
If I can help let me know.

**Comment by f1wade** [comment]
@BottlecapDave what is it that updates these target sensors?
Ie Internet connection for timer,
Octopus rate updating, timer based on the target sensor times.

Wondering if Internet connection or network interruptions will affect it firing?

**Comment by BottlecapDave** [comment]
The integration relies on HA to check the state every minute. The rate information is retrieved in the background using HA reccommmended approaches. I'm already catching any exceptions so lack of internet connections shouldn't effect it. I've made some changes in the latest release which will hopefully make this more reliable.

**Comment by stefano-bortolotti** [comment]
Hi @BottlecapDave, I've installed the home mini device yesterday by going to the "Octopus Energy" integration in HA and ticking the "I have a mini ..." checkbox. 
Today I noticed the since yesterday all my target sensors have stopped working(as in they don't trigger my automations) and I've not yet found the reason. 
The target sensors shows the correct data, example: 
```
Name: water_heater_morning_schedule
Hours: 1.5
Type: Intermittent
MPAN: '1030034828671'
rolling_target: false
last_rates: true
Start time: '02:30'
End time: '08:30'
kind: target_rate
is_target_export: false
target_times:
  - value_inc_vat: 0
    valid_from: '2023-10-06T02:00:00+00:00'
    valid_to: '2023-10-06T02:30:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-22-11-25-A
    is_capped: false
  - value_inc_vat: 0.063
    valid_from: '2023-10-06T02:30:00+00:00'
    valid_to: '2023-10-06T03:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-22-11-25-A
    is_capped: false
  - value_inc_vat: 0
    valid_from: '2023-10-06T03:30:00+00:00'
    valid_to: '2023-10-06T04:00:00+00:00'
    tariff_code: E-1R-AGILE-FLEX-22-11-25-A
    is_capped: false
overall_average_cost: 0.021p
overall_min_cost: 0.0p
overall_max_cost: 0.063p
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: '2023-10-06T02:00:00+00:00'
next_duration_in_hours: 1
next_average_cost: 0.0315p
next_min_cost: 0.0p
next_max_cost: 0.063p
icon: mdi:camera-timer
friendly_name: Octopus Energy Target water_heater_morning_schedule

```
but the automation trigger is not triggered at the listed times, my trigger YMAL: 
```
platform: template
value_template: >-
  {% if
  is_state('binary_sensor.octopus_energy_target_water_heater_morning_schedule',
  'on') %}
    True
  {% else %}
    False
  {% endif %}
for:
  hours: 0
  minutes: 0
  seconds: 15
```
Reading the above thread I wonder if the mini is related to the issue I'm experiencing since the change coincides with the triggers issue. 
Let me know if I can provide more info. 
Thanks

**Comment by BottlecapDave** [comment]
I don't think it has anything to do with the mini, as the two sensors have nothing to do with each other, but rather changing settings without HA restarts. I believe I've fixed this issue in the latest release. Please try upgrading to the latest release, restarting your HA instance and observing results.

**Comment by stefano-bortolotti** [comment]
Ok. Just saw you have a new version from an hour ago. I'm updating it and will test again later today.

**Comment by f1wade** [comment]
> Update I change to 2 mins and it worked, and then 5 mins and it worked.

Correction when on 5 mins, some target triggers didn't fire.

**Comment by jonathh21** [comment]
To add my peneth, I have experienced target rate sensors stopping working.

They show a time, which comes and goes and never 'fires'.

Some combination of reloading that sensor, changing the configuration for it or reloading the entire integration works - by which point the dryer hasn't come on by morning, kids clothes aren't dry and I am on the dog house!

**Comment by BottlecapDave** [comment]
@jonathh21 what version of the integration are you using? I released a new version yesterday, where it had some additional improvements. As I've mentioned in other threads, the sensors are setup as per HA guidlines, so I'm wondering if there's an underlying issue somewhere. Out of interest, what is your HA instance running on?

**Comment by jonathh21** [comment]
Hi, thanks for the response, I was a few versions behind so maybe that was it?

However as of right now I have a number of sensors that had targeted 1130, which still show that as the target and didn't fire (see attachments)

![Screenshot_20231015-115858](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/13969744/5d53b5b7-15e5-40fc-a204-27c8d11e4290)
![Screenshot_20231015-115906](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/13969744/75330c09-e0c9-49e0-af27-c3266cf7bfa7)

Their configuration is unremarkable, I am an agile customer and am still working out the best start time but typically they are set to 17:00-17:00, and configured to re-evaluate. Assuming that will give me 'the best price' available following a re-evaluation, followed by the 2nd and so on.

**Comment by jonathh21** [comment]
As an asside a 'reload' on one of the target entities caused it to select a new time that has come and it has fired, but the rest are still showing 1130 as per the screenshot.

**Comment by BottlecapDave** [comment]
Thanks for the update. If the target rate sensor has calculated when to come on, then it should come on during that time (based on what I can understand from HA achitecture). v8.4.0 set a setting which _should_ always reevaluate the state of any associated entities regardless if the underlying data has changed, which could have helped your situation (if you were on before this). I've also added timeouts to OE API requests, which could have caused delays in sensors updating. I've added some additional logging to my instance and it looks like the state is being evaluated every minute (as expected), but I'll continue to monitor. I assume you don't have any errors in your logs that might be associated with the target rate sensors?

**Comment by BottlecapDave** [comment]
@jonathh21 Have you updated your version of the intergation to the latest and still seeing the issue? In my debugging, the sensor is being evaluated every minute so I'm not too sure why they're not triggering

**Comment by jonathh21** [comment]
Hi yes, apologies for the tardy reply. Combination of bedding in and being lazy.

It has been working without a hitch since I updated everything.

Not one missed and I have alerts for the start of them all so I keenly monitor.

Looking forward to trying the 'offset' on the energy usage download. Previously I had it labelled as 'yesterdays usage ' and had to mentally offset on the graph

**Comment by BottlecapDave** [comment]
Thanks for the update. I'm going to close this, as it looks like it's been fixed. If you are still having issues, please raise a separate ticket.
